import { join } from 'node:path'
import { stat, readdir, rm } from 'node:fs/promises'
import { loadJsonFileWithBackup, writeJsonFileAtomic } from '../persistence/jsonFile.ts'
import type { AppUpdateCheckResult, AppUpdatePreferences } from '../../shared/appUpdate.ts'
import { DEFAULT_APP_UPDATE_PREFERENCES } from '../../shared/appUpdate.ts'
import { isUpdateAsset, type UpdateAsset } from './appUpdateRelease.ts'

export interface UpdateRecord {
  preferences: AppUpdatePreferences
  checkedAt: number
  check: AppUpdateCheckResult | null
  asset: UpdateAsset | null
  ready: UpdateAsset | null
  pendingInstall: string | null
}
export class AppUpdateRepository {
  readonly directory: string
  constructor(directory: string) {
    this.directory = directory
  }
  installer(asset: UpdateAsset): string {
    return join(this.directory, `${asset.sha256}-${asset.name}`)
  }
  partial(asset: UpdateAsset): string {
    return this.installer(asset) + '.part'
  }

  read(): UpdateRecord {
    const loaded = loadJsonFileWithBackup(join(this.directory, 'state.json'), {
      label: 'application update state',
      maxBytes: 512 * 1024,
      validate: (v: unknown): v is Record<string, unknown> =>
        !!v && typeof v === 'object' && !Array.isArray(v)
    })
    const raw = loaded.status === 'missing' ? {} : loaded.value
    const prefs = raw.preferences as Partial<AppUpdatePreferences> | undefined
    const preferences = { ...DEFAULT_APP_UPDATE_PREFERENCES }
    if (prefs && typeof prefs === 'object') {
      if (typeof prefs.autoCheck === 'boolean') preferences.autoCheck = prefs.autoCheck
      if (prefs.channel === 'stable' || prefs.channel === 'preview')
        preferences.channel = prefs.channel
      if ([6, 24, 72].includes(prefs.checkIntervalHours ?? 0))
        preferences.checkIntervalHours = prefs.checkIntervalHours!
      if (typeof prefs.skippedVersion === 'string' && prefs.skippedVersion.length <= 128)
        preferences.skippedVersion = prefs.skippedVersion
      if (typeof prefs.remindAfter === 'number' && Number.isFinite(prefs.remindAfter))
        preferences.remindAfter = prefs.remindAfter
    }
    return {
      preferences,
      checkedAt:
        typeof raw.checkedAt === 'number' && Number.isFinite(raw.checkedAt) ? raw.checkedAt : 0,
      // Cached UI metadata never authorizes a download or an installation.
      check:
        raw.check &&
        typeof raw.check === 'object' &&
        typeof (raw.check as AppUpdateCheckResult).hasUpdate === 'boolean'
          ? (raw.check as AppUpdateCheckResult)
          : null,
      asset: isUpdateAsset(raw.asset) ? raw.asset : null,
      ready: isUpdateAsset(raw.ready) ? raw.ready : null,
      pendingInstall: typeof raw.pendingInstall === 'string' ? raw.pendingInstall : null
    }
  }
  write(record: UpdateRecord): void {
    writeJsonFileAtomic(join(this.directory, 'state.json'), JSON.stringify(record), {
      label: 'application update state',
      maxBytes: 512 * 1024,
      validate: (v: unknown): v is UpdateRecord => !!v && typeof v === 'object'
    })
  }
  async size(path: string): Promise<number> {
    try {
      const info = await stat(path)
      return info.isFile() ? info.size : 0
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return 0
      throw error
    }
  }
  async remove(asset: UpdateAsset): Promise<void> {
    await rm(this.installer(asset), { force: true })
    await rm(this.partial(asset), { force: true })
  }
  async cleanup(keep: UpdateAsset[]): Promise<void> {
    const retained = new Set(keep.flatMap((a) => [this.installer(a), this.partial(a)]))
    let entries: string[]
    try {
      entries = await readdir(this.directory)
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return
      throw error
    }
    // Only remove files generated by this updater, never traverse subdirectories.
    for (const entry of entries) {
      if (!/^[a-f0-9]{64}-[\w.() -]+\.exe(?:\.part)?$/i.test(entry)) continue
      const path = join(this.directory, entry)
      if (!retained.has(path)) await rm(path, { force: true })
    }
  }
}
